### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?

### ISSUE THREAD

**Issue by erdalkaraca** [esl-epfl/gotman_1982#1]
Cloned the repo and run the main() ending with this exception:

`AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?`

It seems nptyping 2.5.0 which is installed by default is not compatible with the dependency numpy>=1.25

**Comment by jon-dan** [comment]
Hello,
Thank you for your bug report.

I am unable to reproduce the error you reported.

I can successfully build and run the docker image, which installs all dependencies.

(The docker image I just built included numpy 1.26.4)

**Comment by jon-dan** [comment]
I just updated the [timescoring](https://github.com/esl-epfl/timescoring/) library, which might have been causing you problems.
It relied on nptyping which seems irrelevant with recent numpy typing.

This might solve your issues ?

**Comment by erdalkaraca** [comment]
yes, the problem does not occur anymore - I am not yet using the Docker environment (yet) to try out the code, first

thanks!
